<?php
/**
 * Index.inc
 *
 * This file contains the Controller_Index class.
 *
 * PHP Version 4 and 5
 *
 * @category Application
 * @package  Controller
 * @author   Tiago Seixas <tiagoafseixas@gmail.com>
 * @license  GPLv3 http://www.gnu.org/licenses/gpl.html
 * @version  SVN: 1
 */
/**
 * Controller_Index
 *
 * @category Application
 * @package  Controller
 * @author   Tiago Seixas <tiagoafseixas@gmail.com>
 * @license  GPLv3 http://www.gnu.org/licenses/gpl.html
 * @version  Release: 1
 */
class Controller_Index extends Framework_Controller
{
    /**
     * Initializes the controller.
     * 
     * @return void
     */
    public function init()
    {
    }
    /**
     * The index action.
     * 
     * @return void
     */
    public function index()
    {
    }
    /**
     * Loads the contact page
     * 
     * @return void
     */
    public function contact()
    {
    }
    /**
     * Loads the help page.
     * 
     * @return void
     */
    public function help()
    {
    }
}
