<?php
/**
 * Error.inc
 *
 * This file contains the Controller_Error class.
 *
 * @category Application
 * @package  Controller
 * @author   Tiago Seixas <tiagoafseixas@gmail.com>
 * @license  GPLv3 http://www.gnu.org/licenses/gpl.html
 * @version  SVN: 1
 */
/**
 * Controller_Error
 *
 * Handles all the errors in the application.
 *
 * @category Application
 * @package  Controller
 * @author   Tiago Seixas <tiagoafseixas@gmail.com>
 * @license  GPLv3 http://www.gnu.org/licenses/gpl.html
 * @version  Release: 1
 */
class Controller_Error extends Framework_Controller
{
    /**
     * Initializes the controller.
     * 
     * @return void
     */
    public function init()
    {
    }

    /**
     * Redirects to the prohibited action
     * 
     * @return void
     */
    public function prohibited()
    {
    }
    /**
     * Redirects to the notFound action
     * 
     * @return void
     */
    public function notFound()
    {
    }
    /**
     * Redirects to the application action
     * 
     * @return void
     */
    public function application()
    {
    }
}